import { ErrorCode, McpError } from "@modelcontextprotocol/sdk/types.js";
import { ToolModule } from "../types.js";
import { gistContent, mcpGist } from "../utils.js";

const PUBLIC_GIST_FOOTER = `

---

*This gist was generated by Claude Code. Please verify any information before relying on it.*
`;

export default {
    definitions: [
        {
            name: "create_private_gist",
            description: "Create a new private GitHub Gist",
            inputSchema: {
                type: "object",
                properties: {
                    description: {
                        type: "string",
                        description: "Description of the Gist",
                    },
                    filename: {
                        type: "string",
                        description:
                            "Name of the file to create. Defaults to README.md.",
                        default: "README.md",
                    },
                    content: {
                        type: "string",
                        description: "Contents of the new file",
                    },
                },
                required: ["description", "content"],
            },
        },
        {
            name: "create_public_gist",
            description:
                "Create a new public GitHub Gist. A note will be appended advising readers to verify the content.",
            inputSchema: {
                type: "object",
                properties: {
                    description: {
                        type: "string",
                        description: "Description of the Gist",
                    },
                    filename: {
                        type: "string",
                        description:
                            "Name of the file to create. Defaults to README.md.",
                        default: "README.md",
                    },
                    content: {
                        type: "string",
                        description: "Contents of the new file",
                    },
                },
                required: ["description", "content"],
            },
        },
        {
            name: "update_gist",
            description: "Update the content of a file in a gist",
            inputSchema: {
                type: "object",
                properties: {
                    id: {
                        type: "string",
                        description: "The ID of the gist",
                    },
                    filename: {
                        type: "string",
                        description: "The name of the file to update",
                    },
                    content: {
                        type: "string",
                        description: "The new content for the file",
                    },
                },
                required: ["id", "filename", "content"],
            },
        },
        {
            name: "delete_gist",
            description: "Delete a GitHub Gist by ID",
            inputSchema: {
                type: "object",
                properties: {
                    id: {
                        type: "string",
                        description: "The ID of the Gist to delete",
                    },
                },
                required: ["id"],
            },
        },
    ],

    handlers: {
        create_private_gist: async (args, context) => {
            const {
                description = "",
                filename = "README.md",
                content = "",
            } = args;

            if (!description || !content) {
                throw new McpError(
                    ErrorCode.InvalidParams,
                    "Description and content are required"
                );
            }

            const { data: gist } = await context.axiosInstance.post("", {
                description,
                public: false,
                files: {
                    [filename as string]: {
                        content: gistContent(content as string),
                    },
                },
            });

            context.gistStore.add(gist);

            return mcpGist(gist);
        },

        create_public_gist: async (args, context) => {
            const {
                description = "",
                filename = "README.md",
                content = "",
            } = args;

            if (!description || !content) {
                throw new McpError(
                    ErrorCode.InvalidParams,
                    "Description and content are required"
                );
            }

            const contentWithFooter = (content as string) + PUBLIC_GIST_FOOTER;

            const { data: gist } = await context.axiosInstance.post("", {
                description,
                public: true,
                files: {
                    [filename as string]: {
                        content: gistContent(contentWithFooter),
                    },
                },
            });

            context.gistStore.add(gist);

            return mcpGist(gist);
        },

        update_gist: async (args, context) => {
            const { id, filename, content } = args as {
                id: string;
                filename: string;
                content: string;
            };

            if (!id || !filename || !content) {
                throw new McpError(
                    ErrorCode.InvalidParams,
                    "ID, filename, and content are required"
                );
            }

            const response = await context.axiosInstance.patch(`/${id}`, {
                files: {
                    [filename]: {
                        content: gistContent(content),
                    },
                },
            });

            context.gistStore.update(response.data);

            return "Gist updated successfully";
        },

        delete_gist: async ({ id }, context) => {
            await context.axiosInstance.delete(`/${id}`);

            context.gistStore.remove(id as string);

            return "Successfully deleted gist";
        },
    },
} as ToolModule;
